steps:
  # Generate .env file from app.yaml
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        grep 'env_variables:' -A 1000 app.yaml | tail -n +2 | sed 's/^  //g' > .env

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA']

  # Deploy container image to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud app deploy app.yaml --image-url=gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA

images:
  - gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY